//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CINEMAEntities : DbContext
    {
        public CINEMAEntities()
            : base("name=CINEMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBCustomer> TBCustomer { get; set; }
        public virtual DbSet<TBMovie> TBMovie { get; set; }
        public virtual DbSet<TBMovieGenres> TBMovieGenres { get; set; }
        public virtual DbSet<TBReceipt> TBReceipt { get; set; }
        public virtual DbSet<TBRoom> TBRoom { get; set; }
        public virtual DbSet<TBRoomType> TBRoomType { get; set; }
        public virtual DbSet<TBSchedule> TBSchedule { get; set; }
        public virtual DbSet<TBSeat> TBSeat { get; set; }
        public virtual DbSet<TBSeatBooking> TBSeatBooking { get; set; }
        public virtual DbSet<TBSeatType> TBSeatType { get; set; }
        public virtual DbSet<TBStaff> TBStaff { get; set; }
    }
}
