//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBRoom()
        {
            this.TBSeat = new HashSet<TBSeat>();
            this.TBSchedule = new HashSet<TBSchedule>();
        }
    
        public int room_id { get; set; }
        public string room_name { get; set; }
        public Nullable<int> room_type_id { get; set; }
        public int room_number_of_seat { get; set; }
        public int room_number_of_row { get; set; }
        public bool is_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBSeat> TBSeat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBSchedule> TBSchedule { get; set; }
        public virtual TBRoomType TBRoomType { get; set; }
    }
}
