//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBSeat()
        {
            this.TBSeatBooking = new HashSet<TBSeatBooking>();
        }
    
        public int seat_id { get; set; }
        public string seat_name { get; set; }
        public int room_id { get; set; }
        public Nullable<int> seat_type_id { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual TBRoom TBRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBSeatBooking> TBSeatBooking { get; set; }
        public virtual TBSeatType TBSeatType { get; set; }
    }
}
