//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSeatBooking
    {
        public int seat_booking_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public int seat_id { get; set; }
        public int receipt_id { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual TBReceipt TBReceipt { get; set; }
        public virtual TBSchedule TBSchedule { get; set; }
        public virtual TBSeat TBSeat { get; set; }
    }
}
